<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aevatar" />
        <PackageReference Include="Aevatar.Core.Abstractions" />
        <PackageReference Include="Microsoft.Orleans.Core.Abstractions" />
        <PackageReference Include="Microsoft.Orleans.Server" />
        <PackageReference Include="Microsoft.Orleans.Streaming" />
        <PackageReference Include="Orleans.Streams.Kafka" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" />
        <PackageReference Include="Aevatar.SignalR" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TokenUsageProjection.GAgents\TokenUsageProjection.GAgents.csproj" />
    </ItemGroup>

</Project>
